language: python
install:
  - pip install -U pip wheel tox codecov
script:
  - tox
matrix:
  include:
    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38
    - name: Lint
      python: 3.8
      env: TOXENV=lint
    - name: Check format
      python: 3.8
      env: TOXENV=fmt
after_success:
  - codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: xJdHpE+llZPcb03rw1ZWQi4Q4thoNOQXgRfZik3V1iTIHmqEUGMVjgGrKIS9+044fE7VYDYxWjWZsJcS+hg9SyJnAfjBbpMjHiVPw0z+DmI5RcB+kvtX1aHqUAQ6smdQw488MayX25rmSSNm+Hju36P0hArnMPqVaUk6rQGS//AdWpABRbWLxAX9x2bnmzKwTE7fVvAtL5S3Cm/GVoz+B/hBbl+WXBwBt/zcmxp03cknrMklXBmnBbGmyfKHkkFFxySwMA5f2XnmW4uGXWRlmcbWJy6byNW59l1zN+D1EZgnVfQBwjF3LsVbXLs1PYjsCpTwHQ4ws15vIjo1e5DI/qW+CRSrosDlOLG5eSyTRhtWnMV7xU+8Qn82MP2qgSS+2wlT6lfRcsUJvETK2Ce/hrF7MAZR2Tt6/3FWrx7xoLnjxi3X2Q6WUIqtXSEVIuigo4uwRlGubM6llg1euouoBzAtFiT1fsBOrA9GK2/KzO4Oh7DB08wrORbIxZDKpQBvCA9EJIEVpX5MnWOXlNAOyzJ2IEAfFzYPIalI/BQ7GpEpYRXJXt7y3tR9Lpbr8LYuvbNRqZUkke/1sltun+z7up8KkUFoAIw6sD61cfaiQwWdJJVDhsANAp+t5WnpA1+hlTaUNhKRNDW/apEupaeyhoRjkhWwoNd1Z0Se9jF9YGI=
  distributions: sdist bdist_wheel
  docs_dir: docs/build/html
  skip_existing: true
  on:
    tags: true
    python: "3.8"
    condition: "$TOXENV = py38"
    repo: mdomke/python-ulid
