[envs.default]
dependencies = [
  "freezegun==1.4.*",
  "pytest-cov==4.1.*",
  "pytest==8.1.*",
]

[envs.default.scripts]
test = "pytest {args:.}"
cov-test = "pytest --cov {args:ulid} --cov-report=term-missing --cov-report=xml"

[envs.lint]
dependencies = [
  "ruff==0.3.*",
  "mypy==1.9.*",
]

[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:ulid}"
style = [
  "ruff format --check --diff {args:.}",
  "ruff check {args:.}",
]
fmt = [
  "ruff format {args:.}",
  "ruff check --fix {args:.}",
]
